[package]
name = "safecmb"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bip39 = "1.0.1"
chrono = "0.4.22"
pdf-canvas = "0.7.0"
rand = "0.8.5"
